######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 5 21:44:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
